package com.tenpen.base.dao;

import com.tenpen.base.domain.model.OrgComplaintRecord;
import com.tenpen.base.domain.model.OrgComplaintRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrgComplaintRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_complaint_record
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int countByExample(OrgComplaintRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_complaint_record
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int deleteByExample(OrgComplaintRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_complaint_record
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_complaint_record
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int insert(OrgComplaintRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_complaint_record
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int insertSelective(OrgComplaintRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_complaint_record
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    List<OrgComplaintRecord> selectByExample(OrgComplaintRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_complaint_record
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    OrgComplaintRecord selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_complaint_record
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int updateByExampleSelective(@Param("record") OrgComplaintRecord record, @Param("example") OrgComplaintRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_complaint_record
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int updateByExample(@Param("record") OrgComplaintRecord record, @Param("example") OrgComplaintRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_complaint_record
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int updateByPrimaryKeySelective(OrgComplaintRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_complaint_record
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int updateByPrimaryKey(OrgComplaintRecord record);
}