package com.tenpen.base.dao;

import com.tenpen.base.domain.model.OrgMemberRecord;
import com.tenpen.base.domain.model.OrgMemberRecordExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface OrgMemberRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_member_record
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int countByExample(OrgMemberRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_member_record
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int deleteByExample(OrgMemberRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_member_record
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_member_record
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int insert(OrgMemberRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_member_record
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int insertSelective(OrgMemberRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_member_record
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    List<OrgMemberRecord> selectByExample(OrgMemberRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_member_record
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    OrgMemberRecord selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_member_record
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int updateByExampleSelective(@Param("record") OrgMemberRecord record, @Param("example") OrgMemberRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_member_record
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int updateByExample(@Param("record") OrgMemberRecord record, @Param("example") OrgMemberRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_member_record
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int updateByPrimaryKeySelective(OrgMemberRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_member_record
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int updateByPrimaryKey(OrgMemberRecord record);

    /**
     * 分页查询
     *
     * @param queryMap 查询条件
     * @return 列表
     */
    List<OrgMemberRecord> selectListByPage(Map<String, Object> queryMap);
}