package com.tenpen.base.dao;

import com.tenpen.base.domain.model.OrgOrdersDetails;
import com.tenpen.base.domain.model.OrgOrdersDetailsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrgOrdersDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_orders_details
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int countByExample(OrgOrdersDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_orders_details
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int deleteByExample(OrgOrdersDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_orders_details
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_orders_details
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int insert(OrgOrdersDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_orders_details
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int insertSelective(OrgOrdersDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_orders_details
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    List<OrgOrdersDetails> selectByExample(OrgOrdersDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_orders_details
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    OrgOrdersDetails selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_orders_details
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int updateByExampleSelective(@Param("record") OrgOrdersDetails record, @Param("example") OrgOrdersDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_orders_details
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int updateByExample(@Param("record") OrgOrdersDetails record, @Param("example") OrgOrdersDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_orders_details
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int updateByPrimaryKeySelective(OrgOrdersDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_orders_details
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int updateByPrimaryKey(OrgOrdersDetails record);
}