package com.tenpen.base.dao;

import com.tenpen.base.domain.model.OrgProducts;
import com.tenpen.base.domain.model.OrgProductsExample;
import com.tenpen.base.dto.product.request.QueryMyProductDTO;
import com.tenpen.base.dto.product.request.QueryProductDTO;
import com.tenpen.base.dto.product.response.MyProductListResponseDTO;
import com.tenpen.base.dto.product.response.ProductListResponseDTO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OrgProductsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_products
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    int countByExample(OrgProductsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_products
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    int deleteByExample(OrgProductsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_products
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_products
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    int insert(OrgProducts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_products
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    int insertSelective(OrgProducts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_products
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    List<OrgProducts> selectByExample(OrgProductsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_products
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    OrgProducts selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_products
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    int updateByExampleSelective(@Param("record") OrgProducts record, @Param("example") OrgProductsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_products
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    int updateByExample(@Param("record") OrgProducts record, @Param("example") OrgProductsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_products
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    int updateByPrimaryKeySelective(OrgProducts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_products
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    int updateByPrimaryKey(OrgProducts record);

    List<ProductListResponseDTO> getProducts(QueryProductDTO request);

    List<MyProductListResponseDTO> getMyProducts(QueryMyProductDTO request);
}