package com.tenpen.base.dao;

import com.tenpen.base.domain.model.OrgPhotosPreviewRecord;
import com.tenpen.base.domain.model.OrgPhotosPreviewRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrgPhotosPreviewRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_photos_preview_record
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int countByExample(OrgPhotosPreviewRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_photos_preview_record
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int deleteByExample(OrgPhotosPreviewRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_photos_preview_record
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_photos_preview_record
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int insert(OrgPhotosPreviewRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_photos_preview_record
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int insertSelective(OrgPhotosPreviewRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_photos_preview_record
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    List<OrgPhotosPreviewRecord> selectByExample(OrgPhotosPreviewRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_photos_preview_record
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    OrgPhotosPreviewRecord selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_photos_preview_record
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int updateByExampleSelective(@Param("record") OrgPhotosPreviewRecord record, @Param("example") OrgPhotosPreviewRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_photos_preview_record
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int updateByExample(@Param("record") OrgPhotosPreviewRecord record, @Param("example") OrgPhotosPreviewRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_photos_preview_record
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int updateByPrimaryKeySelective(OrgPhotosPreviewRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_photos_preview_record
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int updateByPrimaryKey(OrgPhotosPreviewRecord record);
}