package com.tenpen.base.dao;

import com.tenpen.base.domain.model.OrgPlatformTransaction;
import com.tenpen.base.domain.model.OrgPlatformTransactionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrgPlatformTransactionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_platform_transaction
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int countByExample(OrgPlatformTransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_platform_transaction
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int deleteByExample(OrgPlatformTransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_platform_transaction
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_platform_transaction
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int insert(OrgPlatformTransaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_platform_transaction
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int insertSelective(OrgPlatformTransaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_platform_transaction
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    List<OrgPlatformTransaction> selectByExample(OrgPlatformTransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_platform_transaction
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    OrgPlatformTransaction selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_platform_transaction
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int updateByExampleSelective(@Param("record") OrgPlatformTransaction record, @Param("example") OrgPlatformTransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_platform_transaction
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int updateByExample(@Param("record") OrgPlatformTransaction record, @Param("example") OrgPlatformTransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_platform_transaction
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int updateByPrimaryKeySelective(OrgPlatformTransaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_platform_transaction
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int updateByPrimaryKey(OrgPlatformTransaction record);
}