package com.tenpen.base.dao;

import com.tenpen.base.domain.model.OrgUsersIncomesWithdraw;
import com.tenpen.base.domain.model.OrgUsersIncomesWithdrawExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface OrgUsersIncomesWithdrawMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_users_incomes_withdraw
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int countByExample(OrgUsersIncomesWithdrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_users_incomes_withdraw
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int deleteByExample(OrgUsersIncomesWithdrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_users_incomes_withdraw
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_users_incomes_withdraw
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int insert(OrgUsersIncomesWithdraw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_users_incomes_withdraw
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int insertSelective(OrgUsersIncomesWithdraw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_users_incomes_withdraw
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    List<OrgUsersIncomesWithdraw> selectByExample(OrgUsersIncomesWithdrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_users_incomes_withdraw
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    OrgUsersIncomesWithdraw selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_users_incomes_withdraw
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int updateByExampleSelective(@Param("record") OrgUsersIncomesWithdraw record, @Param("example") OrgUsersIncomesWithdrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_users_incomes_withdraw
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int updateByExample(@Param("record") OrgUsersIncomesWithdraw record, @Param("example") OrgUsersIncomesWithdrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_users_incomes_withdraw
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int updateByPrimaryKeySelective(OrgUsersIncomesWithdraw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_users_incomes_withdraw
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int updateByPrimaryKey(OrgUsersIncomesWithdraw record);

    /**
     * 分页查询收益提现明细
     *
     * @param queryMap 查询条件
     * @return 收益明细列表
     */
    List<OrgUsersIncomesWithdraw> selectWithdrawsByPage(Map<String, Object> queryMap);
}