package com.tenpen.base.dao;

import com.tenpen.base.domain.model.OrgUsersAddress;
import com.tenpen.base.domain.model.OrgUsersAddressExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrgUsersAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_users_address
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int countByExample(OrgUsersAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_users_address
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int deleteByExample(OrgUsersAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_users_address
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_users_address
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int insert(OrgUsersAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_users_address
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int insertSelective(OrgUsersAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_users_address
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    List<OrgUsersAddress> selectByExample(OrgUsersAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_users_address
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    OrgUsersAddress selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_users_address
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int updateByExampleSelective(@Param("record") OrgUsersAddress record, @Param("example") OrgUsersAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_users_address
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int updateByExample(@Param("record") OrgUsersAddress record, @Param("example") OrgUsersAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_users_address
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int updateByPrimaryKeySelective(OrgUsersAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_users_address
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    int updateByPrimaryKey(OrgUsersAddress record);
}