package com.tenpen.base.domain.model;

import java.math.BigDecimal;
import java.util.Date;

public class OrgMemberRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_member_record.id
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_member_record.user_id
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_member_record.user_account
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private String userAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_member_record.amount
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_member_record.recharge_type
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private Integer rechargeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_member_record.start_effective
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private Date startEffective;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_member_record.end_effective
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private Date endEffective;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_member_record.order_no
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_member_record.flow_no
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private String flowNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_member_record.creator
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_member_record.create_time
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_member_record.last_updator
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private String lastUpdator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_member_record.last_update_time
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_member_record.last_update_version
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private Integer lastUpdateVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_member_record.remark
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_member_record.id
     *
     * @return the value of org_member_record.id
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_member_record.id
     *
     * @param id the value for org_member_record.id
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_member_record.user_id
     *
     * @return the value of org_member_record.user_id
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_member_record.user_id
     *
     * @param userId the value for org_member_record.user_id
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_member_record.user_account
     *
     * @return the value of org_member_record.user_account
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public String getUserAccount() {
        return userAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_member_record.user_account
     *
     * @param userAccount the value for org_member_record.user_account
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setUserAccount(String userAccount) {
        this.userAccount = userAccount == null ? null : userAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_member_record.amount
     *
     * @return the value of org_member_record.amount
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_member_record.amount
     *
     * @param amount the value for org_member_record.amount
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_member_record.recharge_type
     *
     * @return the value of org_member_record.recharge_type
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public Integer getRechargeType() {
        return rechargeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_member_record.recharge_type
     *
     * @param rechargeType the value for org_member_record.recharge_type
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setRechargeType(Integer rechargeType) {
        this.rechargeType = rechargeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_member_record.start_effective
     *
     * @return the value of org_member_record.start_effective
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public Date getStartEffective() {
        return startEffective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_member_record.start_effective
     *
     * @param startEffective the value for org_member_record.start_effective
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setStartEffective(Date startEffective) {
        this.startEffective = startEffective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_member_record.end_effective
     *
     * @return the value of org_member_record.end_effective
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public Date getEndEffective() {
        return endEffective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_member_record.end_effective
     *
     * @param endEffective the value for org_member_record.end_effective
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setEndEffective(Date endEffective) {
        this.endEffective = endEffective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_member_record.order_no
     *
     * @return the value of org_member_record.order_no
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_member_record.order_no
     *
     * @param orderNo the value for org_member_record.order_no
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_member_record.flow_no
     *
     * @return the value of org_member_record.flow_no
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public String getFlowNo() {
        return flowNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_member_record.flow_no
     *
     * @param flowNo the value for org_member_record.flow_no
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setFlowNo(String flowNo) {
        this.flowNo = flowNo == null ? null : flowNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_member_record.creator
     *
     * @return the value of org_member_record.creator
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_member_record.creator
     *
     * @param creator the value for org_member_record.creator
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_member_record.create_time
     *
     * @return the value of org_member_record.create_time
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_member_record.create_time
     *
     * @param createTime the value for org_member_record.create_time
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_member_record.last_updator
     *
     * @return the value of org_member_record.last_updator
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public String getLastUpdator() {
        return lastUpdator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_member_record.last_updator
     *
     * @param lastUpdator the value for org_member_record.last_updator
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setLastUpdator(String lastUpdator) {
        this.lastUpdator = lastUpdator == null ? null : lastUpdator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_member_record.last_update_time
     *
     * @return the value of org_member_record.last_update_time
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_member_record.last_update_time
     *
     * @param lastUpdateTime the value for org_member_record.last_update_time
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_member_record.last_update_version
     *
     * @return the value of org_member_record.last_update_version
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public Integer getLastUpdateVersion() {
        return lastUpdateVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_member_record.last_update_version
     *
     * @param lastUpdateVersion the value for org_member_record.last_update_version
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setLastUpdateVersion(Integer lastUpdateVersion) {
        this.lastUpdateVersion = lastUpdateVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_member_record.remark
     *
     * @return the value of org_member_record.remark
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_member_record.remark
     *
     * @param remark the value for org_member_record.remark
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}