package com.tenpen.base.domain.model;

import java.math.BigDecimal;
import java.util.Date;

public class OrgOrders {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_orders.id
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_orders.order_no
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_orders.customer_id
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private String customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_orders.customer_name
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private String customerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_orders.customer_account
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private String customerAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_orders.product_count
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private Integer productCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_orders.product_amount_total
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private BigDecimal productAmountTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_orders.pay_channel
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private String payChannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_orders.flow_no
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private String flowNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_orders.status
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_orders.pay_time
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private Date payTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_orders.creator
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_orders.create_time
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_orders.last_update_time
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_orders.last_update_version
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private Integer lastUpdateVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_orders.remark
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_orders.id
     *
     * @return the value of org_orders.id
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_orders.id
     *
     * @param id the value for org_orders.id
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_orders.order_no
     *
     * @return the value of org_orders.order_no
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_orders.order_no
     *
     * @param orderNo the value for org_orders.order_no
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_orders.customer_id
     *
     * @return the value of org_orders.customer_id
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_orders.customer_id
     *
     * @param customerId the value for org_orders.customer_id
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setCustomerId(String customerId) {
        this.customerId = customerId == null ? null : customerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_orders.customer_name
     *
     * @return the value of org_orders.customer_name
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_orders.customer_name
     *
     * @param customerName the value for org_orders.customer_name
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName == null ? null : customerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_orders.customer_account
     *
     * @return the value of org_orders.customer_account
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public String getCustomerAccount() {
        return customerAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_orders.customer_account
     *
     * @param customerAccount the value for org_orders.customer_account
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setCustomerAccount(String customerAccount) {
        this.customerAccount = customerAccount == null ? null : customerAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_orders.product_count
     *
     * @return the value of org_orders.product_count
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public Integer getProductCount() {
        return productCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_orders.product_count
     *
     * @param productCount the value for org_orders.product_count
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setProductCount(Integer productCount) {
        this.productCount = productCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_orders.product_amount_total
     *
     * @return the value of org_orders.product_amount_total
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public BigDecimal getProductAmountTotal() {
        return productAmountTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_orders.product_amount_total
     *
     * @param productAmountTotal the value for org_orders.product_amount_total
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setProductAmountTotal(BigDecimal productAmountTotal) {
        this.productAmountTotal = productAmountTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_orders.pay_channel
     *
     * @return the value of org_orders.pay_channel
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public String getPayChannel() {
        return payChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_orders.pay_channel
     *
     * @param payChannel the value for org_orders.pay_channel
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setPayChannel(String payChannel) {
        this.payChannel = payChannel == null ? null : payChannel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_orders.flow_no
     *
     * @return the value of org_orders.flow_no
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public String getFlowNo() {
        return flowNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_orders.flow_no
     *
     * @param flowNo the value for org_orders.flow_no
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setFlowNo(String flowNo) {
        this.flowNo = flowNo == null ? null : flowNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_orders.status
     *
     * @return the value of org_orders.status
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_orders.status
     *
     * @param status the value for org_orders.status
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_orders.pay_time
     *
     * @return the value of org_orders.pay_time
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_orders.pay_time
     *
     * @param payTime the value for org_orders.pay_time
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_orders.creator
     *
     * @return the value of org_orders.creator
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_orders.creator
     *
     * @param creator the value for org_orders.creator
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_orders.create_time
     *
     * @return the value of org_orders.create_time
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_orders.create_time
     *
     * @param createTime the value for org_orders.create_time
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_orders.last_update_time
     *
     * @return the value of org_orders.last_update_time
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_orders.last_update_time
     *
     * @param lastUpdateTime the value for org_orders.last_update_time
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_orders.last_update_version
     *
     * @return the value of org_orders.last_update_version
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public Integer getLastUpdateVersion() {
        return lastUpdateVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_orders.last_update_version
     *
     * @param lastUpdateVersion the value for org_orders.last_update_version
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setLastUpdateVersion(Integer lastUpdateVersion) {
        this.lastUpdateVersion = lastUpdateVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_orders.remark
     *
     * @return the value of org_orders.remark
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_orders.remark
     *
     * @param remark the value for org_orders.remark
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}