package com.tenpen.base.domain.model;

import java.math.BigDecimal;
import java.util.Date;

public class OrgProducts {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_products.id
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_products.title
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_products.price
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_products.color
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    private String color;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_products.career
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    private String career;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_products.use_time
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    private Integer useTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_products.status
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_products.qty
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    private Integer qty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_products.lock_start_time
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    private Date lockStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_products.lock_end_time
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    private Date lockEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_products.create_by
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_products.creator
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_products.create_time
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_products.last_update_by
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    private String lastUpdateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_products.last_updator
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    private String lastUpdator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_products.last_update_time
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_products.last_update_version
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    private Integer lastUpdateVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_products.remark
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_products.id
     *
     * @return the value of org_products.id
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_products.id
     *
     * @param id the value for org_products.id
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_products.title
     *
     * @return the value of org_products.title
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_products.title
     *
     * @param title the value for org_products.title
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_products.price
     *
     * @return the value of org_products.price
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_products.price
     *
     * @param price the value for org_products.price
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_products.color
     *
     * @return the value of org_products.color
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_products.color
     *
     * @param color the value for org_products.color
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_products.career
     *
     * @return the value of org_products.career
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    public String getCareer() {
        return career;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_products.career
     *
     * @param career the value for org_products.career
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    public void setCareer(String career) {
        this.career = career == null ? null : career.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_products.use_time
     *
     * @return the value of org_products.use_time
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    public Integer getUseTime() {
        return useTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_products.use_time
     *
     * @param useTime the value for org_products.use_time
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    public void setUseTime(Integer useTime) {
        this.useTime = useTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_products.status
     *
     * @return the value of org_products.status
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_products.status
     *
     * @param status the value for org_products.status
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_products.qty
     *
     * @return the value of org_products.qty
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    public Integer getQty() {
        return qty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_products.qty
     *
     * @param qty the value for org_products.qty
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    public void setQty(Integer qty) {
        this.qty = qty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_products.lock_start_time
     *
     * @return the value of org_products.lock_start_time
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    public Date getLockStartTime() {
        return lockStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_products.lock_start_time
     *
     * @param lockStartTime the value for org_products.lock_start_time
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    public void setLockStartTime(Date lockStartTime) {
        this.lockStartTime = lockStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_products.lock_end_time
     *
     * @return the value of org_products.lock_end_time
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    public Date getLockEndTime() {
        return lockEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_products.lock_end_time
     *
     * @param lockEndTime the value for org_products.lock_end_time
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    public void setLockEndTime(Date lockEndTime) {
        this.lockEndTime = lockEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_products.create_by
     *
     * @return the value of org_products.create_by
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_products.create_by
     *
     * @param createBy the value for org_products.create_by
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_products.creator
     *
     * @return the value of org_products.creator
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_products.creator
     *
     * @param creator the value for org_products.creator
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_products.create_time
     *
     * @return the value of org_products.create_time
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_products.create_time
     *
     * @param createTime the value for org_products.create_time
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_products.last_update_by
     *
     * @return the value of org_products.last_update_by
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    public String getLastUpdateBy() {
        return lastUpdateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_products.last_update_by
     *
     * @param lastUpdateBy the value for org_products.last_update_by
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    public void setLastUpdateBy(String lastUpdateBy) {
        this.lastUpdateBy = lastUpdateBy == null ? null : lastUpdateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_products.last_updator
     *
     * @return the value of org_products.last_updator
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    public String getLastUpdator() {
        return lastUpdator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_products.last_updator
     *
     * @param lastUpdator the value for org_products.last_updator
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    public void setLastUpdator(String lastUpdator) {
        this.lastUpdator = lastUpdator == null ? null : lastUpdator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_products.last_update_time
     *
     * @return the value of org_products.last_update_time
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_products.last_update_time
     *
     * @param lastUpdateTime the value for org_products.last_update_time
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_products.last_update_version
     *
     * @return the value of org_products.last_update_version
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    public Integer getLastUpdateVersion() {
        return lastUpdateVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_products.last_update_version
     *
     * @param lastUpdateVersion the value for org_products.last_update_version
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    public void setLastUpdateVersion(Integer lastUpdateVersion) {
        this.lastUpdateVersion = lastUpdateVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_products.remark
     *
     * @return the value of org_products.remark
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_products.remark
     *
     * @param remark the value for org_products.remark
     *
     * @mbggenerated Mon Sep 30 11:05:29 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}