package com.tenpen.base.domain.model;

import java.math.BigDecimal;
import java.util.Date;

public class OrgPlatformTransaction {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_platform_transaction.id
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_platform_transaction.user_id
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_platform_transaction.user_account
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private String userAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_platform_transaction.amount
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_platform_transaction.type
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_platform_transaction.business_id
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private String businessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_platform_transaction.creator
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_platform_transaction.create_time
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_platform_transaction.last_updator
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private String lastUpdator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_platform_transaction.last_update_time
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_platform_transaction.last_update_version
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private Integer lastUpdateVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_platform_transaction.remark
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_platform_transaction.id
     *
     * @return the value of org_platform_transaction.id
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_platform_transaction.id
     *
     * @param id the value for org_platform_transaction.id
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_platform_transaction.user_id
     *
     * @return the value of org_platform_transaction.user_id
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_platform_transaction.user_id
     *
     * @param userId the value for org_platform_transaction.user_id
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_platform_transaction.user_account
     *
     * @return the value of org_platform_transaction.user_account
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public String getUserAccount() {
        return userAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_platform_transaction.user_account
     *
     * @param userAccount the value for org_platform_transaction.user_account
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setUserAccount(String userAccount) {
        this.userAccount = userAccount == null ? null : userAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_platform_transaction.amount
     *
     * @return the value of org_platform_transaction.amount
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_platform_transaction.amount
     *
     * @param amount the value for org_platform_transaction.amount
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_platform_transaction.type
     *
     * @return the value of org_platform_transaction.type
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_platform_transaction.type
     *
     * @param type the value for org_platform_transaction.type
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_platform_transaction.business_id
     *
     * @return the value of org_platform_transaction.business_id
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public String getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_platform_transaction.business_id
     *
     * @param businessId the value for org_platform_transaction.business_id
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setBusinessId(String businessId) {
        this.businessId = businessId == null ? null : businessId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_platform_transaction.creator
     *
     * @return the value of org_platform_transaction.creator
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_platform_transaction.creator
     *
     * @param creator the value for org_platform_transaction.creator
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_platform_transaction.create_time
     *
     * @return the value of org_platform_transaction.create_time
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_platform_transaction.create_time
     *
     * @param createTime the value for org_platform_transaction.create_time
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_platform_transaction.last_updator
     *
     * @return the value of org_platform_transaction.last_updator
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public String getLastUpdator() {
        return lastUpdator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_platform_transaction.last_updator
     *
     * @param lastUpdator the value for org_platform_transaction.last_updator
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setLastUpdator(String lastUpdator) {
        this.lastUpdator = lastUpdator == null ? null : lastUpdator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_platform_transaction.last_update_time
     *
     * @return the value of org_platform_transaction.last_update_time
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_platform_transaction.last_update_time
     *
     * @param lastUpdateTime the value for org_platform_transaction.last_update_time
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_platform_transaction.last_update_version
     *
     * @return the value of org_platform_transaction.last_update_version
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public Integer getLastUpdateVersion() {
        return lastUpdateVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_platform_transaction.last_update_version
     *
     * @param lastUpdateVersion the value for org_platform_transaction.last_update_version
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setLastUpdateVersion(Integer lastUpdateVersion) {
        this.lastUpdateVersion = lastUpdateVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_platform_transaction.remark
     *
     * @return the value of org_platform_transaction.remark
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_platform_transaction.remark
     *
     * @param remark the value for org_platform_transaction.remark
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}