package com.tenpen.base.domain.model;

import java.math.BigDecimal;
import java.util.Date;

public class OrgPhotosStatistics {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_photos_statistics.id
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_photos_statistics.self_photos_id
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private String selfPhotosId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_photos_statistics.preview_amount
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private Integer previewAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_photos_statistics.collection_amount
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private Integer collectionAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_photos_statistics.period
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private String period;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_photos_statistics.income
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private BigDecimal income;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_photos_statistics.create_time
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_photos_statistics.last_update_time
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_photos_statistics.last_update_version
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private Integer lastUpdateVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_photos_statistics.remark
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_photos_statistics.id
     *
     * @return the value of org_photos_statistics.id
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_photos_statistics.id
     *
     * @param id the value for org_photos_statistics.id
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_photos_statistics.self_photos_id
     *
     * @return the value of org_photos_statistics.self_photos_id
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public String getSelfPhotosId() {
        return selfPhotosId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_photos_statistics.self_photos_id
     *
     * @param selfPhotosId the value for org_photos_statistics.self_photos_id
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setSelfPhotosId(String selfPhotosId) {
        this.selfPhotosId = selfPhotosId == null ? null : selfPhotosId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_photos_statistics.preview_amount
     *
     * @return the value of org_photos_statistics.preview_amount
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public Integer getPreviewAmount() {
        return previewAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_photos_statistics.preview_amount
     *
     * @param previewAmount the value for org_photos_statistics.preview_amount
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setPreviewAmount(Integer previewAmount) {
        this.previewAmount = previewAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_photos_statistics.collection_amount
     *
     * @return the value of org_photos_statistics.collection_amount
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public Integer getCollectionAmount() {
        return collectionAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_photos_statistics.collection_amount
     *
     * @param collectionAmount the value for org_photos_statistics.collection_amount
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setCollectionAmount(Integer collectionAmount) {
        this.collectionAmount = collectionAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_photos_statistics.period
     *
     * @return the value of org_photos_statistics.period
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public String getPeriod() {
        return period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_photos_statistics.period
     *
     * @param period the value for org_photos_statistics.period
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setPeriod(String period) {
        this.period = period == null ? null : period.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_photos_statistics.income
     *
     * @return the value of org_photos_statistics.income
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public BigDecimal getIncome() {
        return income;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_photos_statistics.income
     *
     * @param income the value for org_photos_statistics.income
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setIncome(BigDecimal income) {
        this.income = income;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_photos_statistics.create_time
     *
     * @return the value of org_photos_statistics.create_time
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_photos_statistics.create_time
     *
     * @param createTime the value for org_photos_statistics.create_time
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_photos_statistics.last_update_time
     *
     * @return the value of org_photos_statistics.last_update_time
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_photos_statistics.last_update_time
     *
     * @param lastUpdateTime the value for org_photos_statistics.last_update_time
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_photos_statistics.last_update_version
     *
     * @return the value of org_photos_statistics.last_update_version
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public Integer getLastUpdateVersion() {
        return lastUpdateVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_photos_statistics.last_update_version
     *
     * @param lastUpdateVersion the value for org_photos_statistics.last_update_version
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setLastUpdateVersion(Integer lastUpdateVersion) {
        this.lastUpdateVersion = lastUpdateVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_photos_statistics.remark
     *
     * @return the value of org_photos_statistics.remark
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_photos_statistics.remark
     *
     * @param remark the value for org_photos_statistics.remark
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}