package com.tenpen.base.domain.model;

import java.util.Date;

public class OrgUsersAddress {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_users_address.id
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_users_address.user_id
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_users_address.user_account
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private String userAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_users_address.rec_name
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private String recName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_users_address.tel_no
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private String telNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_users_address.rec_address
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private String recAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_users_address.is_defualt
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private String isDefualt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_users_address.creator
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_users_address.create_time
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_users_address.last_updator
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private String lastUpdator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_users_address.last_update_time
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_users_address.last_update_version
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private Integer lastUpdateVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_users_address.remark
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_users_address.id
     *
     * @return the value of org_users_address.id
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_users_address.id
     *
     * @param id the value for org_users_address.id
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_users_address.user_id
     *
     * @return the value of org_users_address.user_id
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_users_address.user_id
     *
     * @param userId the value for org_users_address.user_id
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_users_address.user_account
     *
     * @return the value of org_users_address.user_account
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public String getUserAccount() {
        return userAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_users_address.user_account
     *
     * @param userAccount the value for org_users_address.user_account
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setUserAccount(String userAccount) {
        this.userAccount = userAccount == null ? null : userAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_users_address.rec_name
     *
     * @return the value of org_users_address.rec_name
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public String getRecName() {
        return recName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_users_address.rec_name
     *
     * @param recName the value for org_users_address.rec_name
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setRecName(String recName) {
        this.recName = recName == null ? null : recName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_users_address.tel_no
     *
     * @return the value of org_users_address.tel_no
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public String getTelNo() {
        return telNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_users_address.tel_no
     *
     * @param telNo the value for org_users_address.tel_no
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setTelNo(String telNo) {
        this.telNo = telNo == null ? null : telNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_users_address.rec_address
     *
     * @return the value of org_users_address.rec_address
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public String getRecAddress() {
        return recAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_users_address.rec_address
     *
     * @param recAddress the value for org_users_address.rec_address
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setRecAddress(String recAddress) {
        this.recAddress = recAddress == null ? null : recAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_users_address.is_defualt
     *
     * @return the value of org_users_address.is_defualt
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public String getIsDefualt() {
        return isDefualt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_users_address.is_defualt
     *
     * @param isDefualt the value for org_users_address.is_defualt
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setIsDefualt(String isDefualt) {
        this.isDefualt = isDefualt == null ? null : isDefualt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_users_address.creator
     *
     * @return the value of org_users_address.creator
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_users_address.creator
     *
     * @param creator the value for org_users_address.creator
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_users_address.create_time
     *
     * @return the value of org_users_address.create_time
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_users_address.create_time
     *
     * @param createTime the value for org_users_address.create_time
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_users_address.last_updator
     *
     * @return the value of org_users_address.last_updator
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public String getLastUpdator() {
        return lastUpdator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_users_address.last_updator
     *
     * @param lastUpdator the value for org_users_address.last_updator
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setLastUpdator(String lastUpdator) {
        this.lastUpdator = lastUpdator == null ? null : lastUpdator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_users_address.last_update_time
     *
     * @return the value of org_users_address.last_update_time
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_users_address.last_update_time
     *
     * @param lastUpdateTime the value for org_users_address.last_update_time
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_users_address.last_update_version
     *
     * @return the value of org_users_address.last_update_version
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public Integer getLastUpdateVersion() {
        return lastUpdateVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_users_address.last_update_version
     *
     * @param lastUpdateVersion the value for org_users_address.last_update_version
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setLastUpdateVersion(Integer lastUpdateVersion) {
        this.lastUpdateVersion = lastUpdateVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_users_address.remark
     *
     * @return the value of org_users_address.remark
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_users_address.remark
     *
     * @param remark the value for org_users_address.remark
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}