package com.tenpen.base.dao;

import com.tenpen.base.domain.model.OrgCollectionRecord;
import com.tenpen.base.domain.model.OrgCollectionRecordExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface OrgCollectionRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_collection_record
     *
     * @mbggenerated Thu Sep 26 18:24:11 CST 2019
     */
    int countByExample(OrgCollectionRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_collection_record
     *
     * @mbggenerated Thu Sep 26 18:24:11 CST 2019
     */
    int deleteByExample(OrgCollectionRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_collection_record
     *
     * @mbggenerated Thu Sep 26 18:24:11 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_collection_record
     *
     * @mbggenerated Thu Sep 26 18:24:11 CST 2019
     */
    int insert(OrgCollectionRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_collection_record
     *
     * @mbggenerated Thu Sep 26 18:24:11 CST 2019
     */
    int insertSelective(OrgCollectionRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_collection_record
     *
     * @mbggenerated Thu Sep 26 18:24:11 CST 2019
     */
    List<OrgCollectionRecord> selectByExample(OrgCollectionRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_collection_record
     *
     * @mbggenerated Thu Sep 26 18:24:11 CST 2019
     */
    OrgCollectionRecord selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_collection_record
     *
     * @mbggenerated Thu Sep 26 18:24:11 CST 2019
     */
    int updateByExampleSelective(@Param("record") OrgCollectionRecord record, @Param("example") OrgCollectionRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_collection_record
     *
     * @mbggenerated Thu Sep 26 18:24:11 CST 2019
     */
    int updateByExample(@Param("record") OrgCollectionRecord record, @Param("example") OrgCollectionRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_collection_record
     *
     * @mbggenerated Thu Sep 26 18:24:11 CST 2019
     */
    int updateByPrimaryKeySelective(OrgCollectionRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_collection_record
     *
     * @mbggenerated Thu Sep 26 18:24:11 CST 2019
     */
    int updateByPrimaryKey(OrgCollectionRecord record);

    /**
     * 分页查询收藏记录
     *
     * @param queryMap 查询条件
     * @return 收藏列表
     */
    List<OrgCollectionRecord> selectBookmarksByPage(Map<String, Object> queryMap);
}