package com.tenpen.base.dao;

import com.tenpen.base.domain.model.OrgUsersIncomes;
import com.tenpen.base.domain.model.OrgUsersIncomesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrgUsersIncomesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_users_incomes
     *
     * @mbggenerated Thu Sep 26 17:15:10 CST 2019
     */
    int countByExample(OrgUsersIncomesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_users_incomes
     *
     * @mbggenerated Thu Sep 26 17:15:10 CST 2019
     */
    int deleteByExample(OrgUsersIncomesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_users_incomes
     *
     * @mbggenerated Thu Sep 26 17:15:10 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_users_incomes
     *
     * @mbggenerated Thu Sep 26 17:15:10 CST 2019
     */
    int insert(OrgUsersIncomes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_users_incomes
     *
     * @mbggenerated Thu Sep 26 17:15:10 CST 2019
     */
    int insertSelective(OrgUsersIncomes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_users_incomes
     *
     * @mbggenerated Thu Sep 26 17:15:10 CST 2019
     */
    List<OrgUsersIncomes> selectByExample(OrgUsersIncomesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_users_incomes
     *
     * @mbggenerated Thu Sep 26 17:15:10 CST 2019
     */
    OrgUsersIncomes selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_users_incomes
     *
     * @mbggenerated Thu Sep 26 17:15:10 CST 2019
     */
    int updateByExampleSelective(@Param("record") OrgUsersIncomes record, @Param("example") OrgUsersIncomesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_users_incomes
     *
     * @mbggenerated Thu Sep 26 17:15:10 CST 2019
     */
    int updateByExample(@Param("record") OrgUsersIncomes record, @Param("example") OrgUsersIncomesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_users_incomes
     *
     * @mbggenerated Thu Sep 26 17:15:10 CST 2019
     */
    int updateByPrimaryKeySelective(OrgUsersIncomes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_users_incomes
     *
     * @mbggenerated Thu Sep 26 17:15:10 CST 2019
     */
    int updateByPrimaryKey(OrgUsersIncomes record);
}