package com.tenpen.base.domain.model;

import java.util.Date;

public class OrgPhotos {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_photos.id
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_photos.title
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_photos.total_collection_amout
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private Integer totalCollectionAmout;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_photos.total_preview_amount
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private Integer totalPreviewAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_photos.status
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_photos.is_welfare
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private String isWelfare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_photos.creator
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_photos.create_time
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_photos.last_updator
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private String lastUpdator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_photos.last_update_time
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_photos.last_update_version
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private Integer lastUpdateVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_photos.remark
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_photos.id
     *
     * @return the value of org_photos.id
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_photos.id
     *
     * @param id the value for org_photos.id
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_photos.title
     *
     * @return the value of org_photos.title
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_photos.title
     *
     * @param title the value for org_photos.title
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_photos.total_collection_amout
     *
     * @return the value of org_photos.total_collection_amout
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public Integer getTotalCollectionAmout() {
        return totalCollectionAmout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_photos.total_collection_amout
     *
     * @param totalCollectionAmout the value for org_photos.total_collection_amout
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setTotalCollectionAmout(Integer totalCollectionAmout) {
        this.totalCollectionAmout = totalCollectionAmout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_photos.total_preview_amount
     *
     * @return the value of org_photos.total_preview_amount
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public Integer getTotalPreviewAmount() {
        return totalPreviewAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_photos.total_preview_amount
     *
     * @param totalPreviewAmount the value for org_photos.total_preview_amount
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setTotalPreviewAmount(Integer totalPreviewAmount) {
        this.totalPreviewAmount = totalPreviewAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_photos.status
     *
     * @return the value of org_photos.status
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_photos.status
     *
     * @param status the value for org_photos.status
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_photos.is_welfare
     *
     * @return the value of org_photos.is_welfare
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public String getIsWelfare() {
        return isWelfare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_photos.is_welfare
     *
     * @param isWelfare the value for org_photos.is_welfare
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setIsWelfare(String isWelfare) {
        this.isWelfare = isWelfare == null ? null : isWelfare.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_photos.creator
     *
     * @return the value of org_photos.creator
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_photos.creator
     *
     * @param creator the value for org_photos.creator
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_photos.create_time
     *
     * @return the value of org_photos.create_time
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_photos.create_time
     *
     * @param createTime the value for org_photos.create_time
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_photos.last_updator
     *
     * @return the value of org_photos.last_updator
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public String getLastUpdator() {
        return lastUpdator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_photos.last_updator
     *
     * @param lastUpdator the value for org_photos.last_updator
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setLastUpdator(String lastUpdator) {
        this.lastUpdator = lastUpdator == null ? null : lastUpdator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_photos.last_update_time
     *
     * @return the value of org_photos.last_update_time
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_photos.last_update_time
     *
     * @param lastUpdateTime the value for org_photos.last_update_time
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_photos.last_update_version
     *
     * @return the value of org_photos.last_update_version
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public Integer getLastUpdateVersion() {
        return lastUpdateVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_photos.last_update_version
     *
     * @param lastUpdateVersion the value for org_photos.last_update_version
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setLastUpdateVersion(Integer lastUpdateVersion) {
        this.lastUpdateVersion = lastUpdateVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_photos.remark
     *
     * @return the value of org_photos.remark
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_photos.remark
     *
     * @param remark the value for org_photos.remark
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}