package com.tenpen.base.domain.model;

import java.math.BigDecimal;
import java.util.Date;

public class OrgRecommends {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_recommends.id
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_recommends.cur_page
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private Integer curPage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_recommends.position
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private Integer position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_recommends.status
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_recommends.price
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_recommends.type
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_recommends.effective_period
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private Integer effectivePeriod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_recommends.creator
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_recommends.create_time
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_recommends.last_updator
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private String lastUpdator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_recommends.last_update_time
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_recommends.last_update_version
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private Integer lastUpdateVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_recommends.remark
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_recommends.id
     *
     * @return the value of org_recommends.id
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_recommends.id
     *
     * @param id the value for org_recommends.id
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_recommends.cur_page
     *
     * @return the value of org_recommends.cur_page
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public Integer getCurPage() {
        return curPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_recommends.cur_page
     *
     * @param curPage the value for org_recommends.cur_page
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setCurPage(Integer curPage) {
        this.curPage = curPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_recommends.position
     *
     * @return the value of org_recommends.position
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public Integer getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_recommends.position
     *
     * @param position the value for org_recommends.position
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setPosition(Integer position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_recommends.status
     *
     * @return the value of org_recommends.status
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_recommends.status
     *
     * @param status the value for org_recommends.status
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_recommends.price
     *
     * @return the value of org_recommends.price
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_recommends.price
     *
     * @param price the value for org_recommends.price
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_recommends.type
     *
     * @return the value of org_recommends.type
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_recommends.type
     *
     * @param type the value for org_recommends.type
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_recommends.effective_period
     *
     * @return the value of org_recommends.effective_period
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public Integer getEffectivePeriod() {
        return effectivePeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_recommends.effective_period
     *
     * @param effectivePeriod the value for org_recommends.effective_period
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setEffectivePeriod(Integer effectivePeriod) {
        this.effectivePeriod = effectivePeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_recommends.creator
     *
     * @return the value of org_recommends.creator
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_recommends.creator
     *
     * @param creator the value for org_recommends.creator
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_recommends.create_time
     *
     * @return the value of org_recommends.create_time
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_recommends.create_time
     *
     * @param createTime the value for org_recommends.create_time
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_recommends.last_updator
     *
     * @return the value of org_recommends.last_updator
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public String getLastUpdator() {
        return lastUpdator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_recommends.last_updator
     *
     * @param lastUpdator the value for org_recommends.last_updator
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setLastUpdator(String lastUpdator) {
        this.lastUpdator = lastUpdator == null ? null : lastUpdator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_recommends.last_update_time
     *
     * @return the value of org_recommends.last_update_time
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_recommends.last_update_time
     *
     * @param lastUpdateTime the value for org_recommends.last_update_time
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_recommends.last_update_version
     *
     * @return the value of org_recommends.last_update_version
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public Integer getLastUpdateVersion() {
        return lastUpdateVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_recommends.last_update_version
     *
     * @param lastUpdateVersion the value for org_recommends.last_update_version
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setLastUpdateVersion(Integer lastUpdateVersion) {
        this.lastUpdateVersion = lastUpdateVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_recommends.remark
     *
     * @return the value of org_recommends.remark
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_recommends.remark
     *
     * @param remark the value for org_recommends.remark
     *
     * @mbggenerated Wed Sep 25 16:05:01 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}