package com.tenpen.base.domain.model;

import java.math.BigDecimal;
import java.util.Date;

public class OrgUsersIncomes {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_users_incomes.id
     *
     * @mbggenerated Thu Sep 26 17:15:10 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_users_incomes.user_id
     *
     * @mbggenerated Thu Sep 26 17:15:10 CST 2019
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_users_incomes.user_account
     *
     * @mbggenerated Thu Sep 26 17:15:10 CST 2019
     */
    private String userAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_users_incomes.user_name
     *
     * @mbggenerated Thu Sep 26 17:15:10 CST 2019
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_users_incomes.total_amount
     *
     * @mbggenerated Thu Sep 26 17:15:10 CST 2019
     */
    private BigDecimal totalAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_users_incomes.withdrawal_amount
     *
     * @mbggenerated Thu Sep 26 17:15:10 CST 2019
     */
    private BigDecimal withdrawalAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_users_incomes.balance_amount
     *
     * @mbggenerated Thu Sep 26 17:15:10 CST 2019
     */
    private BigDecimal balanceAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_users_incomes.product_amount
     *
     * @mbggenerated Thu Sep 26 17:15:10 CST 2019
     */
    private BigDecimal productAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_users_incomes.photo_amount
     *
     * @mbggenerated Thu Sep 26 17:15:10 CST 2019
     */
    private BigDecimal photoAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_users_incomes.creator
     *
     * @mbggenerated Thu Sep 26 17:15:10 CST 2019
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_users_incomes.create_time
     *
     * @mbggenerated Thu Sep 26 17:15:10 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_users_incomes.last_updator
     *
     * @mbggenerated Thu Sep 26 17:15:10 CST 2019
     */
    private String lastUpdator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_users_incomes.last_update_time
     *
     * @mbggenerated Thu Sep 26 17:15:10 CST 2019
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_users_incomes.last_update_version
     *
     * @mbggenerated Thu Sep 26 17:15:10 CST 2019
     */
    private Integer lastUpdateVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_users_incomes.remark
     *
     * @mbggenerated Thu Sep 26 17:15:10 CST 2019
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_users_incomes.id
     *
     * @return the value of org_users_incomes.id
     *
     * @mbggenerated Thu Sep 26 17:15:10 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_users_incomes.id
     *
     * @param id the value for org_users_incomes.id
     *
     * @mbggenerated Thu Sep 26 17:15:10 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_users_incomes.user_id
     *
     * @return the value of org_users_incomes.user_id
     *
     * @mbggenerated Thu Sep 26 17:15:10 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_users_incomes.user_id
     *
     * @param userId the value for org_users_incomes.user_id
     *
     * @mbggenerated Thu Sep 26 17:15:10 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_users_incomes.user_account
     *
     * @return the value of org_users_incomes.user_account
     *
     * @mbggenerated Thu Sep 26 17:15:10 CST 2019
     */
    public String getUserAccount() {
        return userAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_users_incomes.user_account
     *
     * @param userAccount the value for org_users_incomes.user_account
     *
     * @mbggenerated Thu Sep 26 17:15:10 CST 2019
     */
    public void setUserAccount(String userAccount) {
        this.userAccount = userAccount == null ? null : userAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_users_incomes.user_name
     *
     * @return the value of org_users_incomes.user_name
     *
     * @mbggenerated Thu Sep 26 17:15:10 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_users_incomes.user_name
     *
     * @param userName the value for org_users_incomes.user_name
     *
     * @mbggenerated Thu Sep 26 17:15:10 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_users_incomes.total_amount
     *
     * @return the value of org_users_incomes.total_amount
     *
     * @mbggenerated Thu Sep 26 17:15:10 CST 2019
     */
    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_users_incomes.total_amount
     *
     * @param totalAmount the value for org_users_incomes.total_amount
     *
     * @mbggenerated Thu Sep 26 17:15:10 CST 2019
     */
    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_users_incomes.withdrawal_amount
     *
     * @return the value of org_users_incomes.withdrawal_amount
     *
     * @mbggenerated Thu Sep 26 17:15:10 CST 2019
     */
    public BigDecimal getWithdrawalAmount() {
        return withdrawalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_users_incomes.withdrawal_amount
     *
     * @param withdrawalAmount the value for org_users_incomes.withdrawal_amount
     *
     * @mbggenerated Thu Sep 26 17:15:10 CST 2019
     */
    public void setWithdrawalAmount(BigDecimal withdrawalAmount) {
        this.withdrawalAmount = withdrawalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_users_incomes.balance_amount
     *
     * @return the value of org_users_incomes.balance_amount
     *
     * @mbggenerated Thu Sep 26 17:15:10 CST 2019
     */
    public BigDecimal getBalanceAmount() {
        return balanceAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_users_incomes.balance_amount
     *
     * @param balanceAmount the value for org_users_incomes.balance_amount
     *
     * @mbggenerated Thu Sep 26 17:15:10 CST 2019
     */
    public void setBalanceAmount(BigDecimal balanceAmount) {
        this.balanceAmount = balanceAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_users_incomes.product_amount
     *
     * @return the value of org_users_incomes.product_amount
     *
     * @mbggenerated Thu Sep 26 17:15:10 CST 2019
     */
    public BigDecimal getProductAmount() {
        return productAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_users_incomes.product_amount
     *
     * @param productAmount the value for org_users_incomes.product_amount
     *
     * @mbggenerated Thu Sep 26 17:15:10 CST 2019
     */
    public void setProductAmount(BigDecimal productAmount) {
        this.productAmount = productAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_users_incomes.photo_amount
     *
     * @return the value of org_users_incomes.photo_amount
     *
     * @mbggenerated Thu Sep 26 17:15:10 CST 2019
     */
    public BigDecimal getPhotoAmount() {
        return photoAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_users_incomes.photo_amount
     *
     * @param photoAmount the value for org_users_incomes.photo_amount
     *
     * @mbggenerated Thu Sep 26 17:15:10 CST 2019
     */
    public void setPhotoAmount(BigDecimal photoAmount) {
        this.photoAmount = photoAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_users_incomes.creator
     *
     * @return the value of org_users_incomes.creator
     *
     * @mbggenerated Thu Sep 26 17:15:10 CST 2019
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_users_incomes.creator
     *
     * @param creator the value for org_users_incomes.creator
     *
     * @mbggenerated Thu Sep 26 17:15:10 CST 2019
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_users_incomes.create_time
     *
     * @return the value of org_users_incomes.create_time
     *
     * @mbggenerated Thu Sep 26 17:15:10 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_users_incomes.create_time
     *
     * @param createTime the value for org_users_incomes.create_time
     *
     * @mbggenerated Thu Sep 26 17:15:10 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_users_incomes.last_updator
     *
     * @return the value of org_users_incomes.last_updator
     *
     * @mbggenerated Thu Sep 26 17:15:10 CST 2019
     */
    public String getLastUpdator() {
        return lastUpdator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_users_incomes.last_updator
     *
     * @param lastUpdator the value for org_users_incomes.last_updator
     *
     * @mbggenerated Thu Sep 26 17:15:10 CST 2019
     */
    public void setLastUpdator(String lastUpdator) {
        this.lastUpdator = lastUpdator == null ? null : lastUpdator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_users_incomes.last_update_time
     *
     * @return the value of org_users_incomes.last_update_time
     *
     * @mbggenerated Thu Sep 26 17:15:10 CST 2019
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_users_incomes.last_update_time
     *
     * @param lastUpdateTime the value for org_users_incomes.last_update_time
     *
     * @mbggenerated Thu Sep 26 17:15:10 CST 2019
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_users_incomes.last_update_version
     *
     * @return the value of org_users_incomes.last_update_version
     *
     * @mbggenerated Thu Sep 26 17:15:10 CST 2019
     */
    public Integer getLastUpdateVersion() {
        return lastUpdateVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_users_incomes.last_update_version
     *
     * @param lastUpdateVersion the value for org_users_incomes.last_update_version
     *
     * @mbggenerated Thu Sep 26 17:15:10 CST 2019
     */
    public void setLastUpdateVersion(Integer lastUpdateVersion) {
        this.lastUpdateVersion = lastUpdateVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_users_incomes.remark
     *
     * @return the value of org_users_incomes.remark
     *
     * @mbggenerated Thu Sep 26 17:15:10 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_users_incomes.remark
     *
     * @param remark the value for org_users_incomes.remark
     *
     * @mbggenerated Thu Sep 26 17:15:10 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}